inserir em papel (ID, nome) valores ( 1 , ' ROLE_USER ' );
inserir em papel (ID, nome) valores ( 2 , ' ROLE_ADMIN ' );

insira no usuário (id, nome, email, login, senha) valores ( 1 , ' Ricardo Lecheta ' , ' rlecheta@gmail.com ' , ' rlecheta ' , ' $ 2a $ 10 $ HKveMsPlst41Ie2LQgpijO691lUtZ8cLfcliAO1DD9TtZxEpaEpaEoJe ' );
inserir utilizador (id, nome, email, login, Senha) valores ( 2 , ' admin ' , ' admin@gmail.com ' , ' administrador ' , ' $ 2a $ 10 $ HKveMsPlst41Ie2LQgpijO691lUtZ8cLfcliAO1DD9TtZxEpaEoJe ' );
inserir no utilizador (ID, nome, e-mail, de login, Senha) valores ( 3 , ' Utilizador ' , ' user@gmail.com ' , ' utilizador ' , ' $ 2-A $ 10 $ HKveMsPlst41Ie2LQgpijO691lUtZ8cLfcliAO1DD9TtZxEpaEoJe ' );

inserir em user_roles (user_id, role_id) valores ( 1 , 1 );
inserir em user_roles (user_id, role_id) valores ( 2 , 2 );
inserir em user_roles (user_id, role_id) valores ( 3 , 1 );

inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALUES ( ' Tucker 1948 ' , ' Descrição Tucker 1948 ' , ' http://www.livroandroid.com.br/livro/carros/classicos/ Tucker.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/tucker.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Chevrolet Corvette ' , ' Descrição Chevrolet Corvette ' , ' http://www.livroandroid.com.br/livro/carros/classicos/ Chevrolet_Corvette.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/corvette.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Chevrolet Impala Coupe ' , ' Descrição Chevrolet Impala Coupe ' , ' http://www.livroandroid.com.br/livro/carros/ classicos / Chevrolet_Impala_Coupe.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/chevrolet_impala.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Cadillac Deville Convertible ' , ' Descrição Cadillac Deville Convertible ' , ' http://www.livroandroid.com.br/livro/carros/ classicos / Cadillac_Deville_Convertible.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/cadillac_deville.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Chevrolet Bel-Air ' , ' Descrição Chevrolet Bel-Air ' , ' http://www.livroandroid.com.br/livro/ carros / classicos / Chevrolet_BelAir.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/chevrolet_bel_air.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Cadillac Eldorado ' , ' Descrição Cadillac Eldorado ' , ' http://www.livroandroid.com.br/livro/carros/classicos/ Cadillac_Eldorado.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/cadillac_eldorado.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Ferrari 250 GTO ' , ' Descrição Ferrari 250 GTO ' , ' http://www.livroandroid.com.br/livro/carros/ classicos / Ferrari_250_GTO.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/ferrari_gto.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Dodge Challenger ' , ' Descrição Dodge Challenger ' , ' http://www.livroandroid.com.br/livro/carros/classicos/ Dodge_Challenger.png ' , ' http://www.livroandroid.com.br/livro/carros/classicos/dodge_challenger.mp4 ' , ' ' , ' ' , ' clássicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Camaro SS 1969 ' , ' Descrição Camaro SS 1969 ' , ' http://www.livroandroid.com.br/livro/carros/ classicos / Camaro_SS.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/camaro_ss.mp4 ' ' -23.564224 ' ' -46.653156 ' ' classicos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Ford Mustang 1976 ' , ' Descrição Ford Mustang 1976 ' , ' http://www.livroandroid.com.br/livro/carros/ classicos / Ford_Mustang.png ' ' http://www.livroandroid.com.br/livro/carros/classicos/ford_mustang.mp4 ' ' -23,564224 ' ' -46,653156 ' ' classicos ' );


inserir no carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Ferrari FF ' , ' Descrição Ferrari FF ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/ Ferrari_FF.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/ferrari_ff.mp4 ' , ' 44.532218 ' , ' 10.864019 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' AUDI GT Spyder ' , ' Descrição AUDI GT Spyder ' , ' http://www.livroandroid.com.br/livro/carros/ esportivos / Audi_Spyder.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/audi_gt.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Porsche Panamera ' , ' Descrição Porsche Panamera ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/ Porsche_Panamera.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/porsche_panamera.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Lamborghini Aventador ' , ' Descrição Lamborghini Aventador ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/ Lamborghini_Aventador.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/lamborghini_aventador.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir no carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Chevrolet Corvette Z06 ' , ' Descrição Chevrolet Corvette Z06 ' , ' http://www.livroandroid.com.br/livro/carros/ esportivos / Chevrolet_Corvette_Z06.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/chevrolet_corvette.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' BMW M5 ' , ' Descrição BMW M5 ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/ BMW.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/bmw-m5.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em caminhão (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Renault Megane RS Trophy ' , ' Descrição Renault Megane RS Trophy ' , ' http://www.livroandroid.com.br/livro/ carros / esportivos / Renault_Megane_Trophy.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/renault_megane.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Maserati Grancabrio Sport ' , ' Descrição Maserati Grancabrio Sport ' , ' http://www.livroandroid.com.br/livro/carros/ esportivos / Maserati_Grancabrio_Sport.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/renault_megane.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' McLAREN MP4-12C ' , ' Descrição McLAREN MP4-12C ' , ' http://www.livroandroid.com.br/livro/ carros / esportivos / McLAREN.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/mcLaren.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' MERCEDES-BENZ C63 AMG ' , ' Descrição MERCEDES-BENZ C63 AMG ' , ' http://www.livroandroid.com.br/ livro / carros / esportivos / MERCEDES_BENZ_AMG.png ' , ' http://www.livroandroid.com.br/livro/carros/esportivos/mercedes.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' esportivos ' );


inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Bugatti Veyron ' , ' Descrição Bugatti Veyron ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Bugatti_Veyron.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/bugatti_veyron.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Ferrari Enzo ' , ' Descrição Ferrari Enzo ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Ferrari_Enzo.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ferrari_enzo.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Lamborghini Reventon ' , ' Descrição Lamborghini Reventon ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Lamborghini_Reventon.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/lamborghini _reventon.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Leblanc Mirabeau ' , ' Descrição Leblanc Mirabeau ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Leblanc_Mirabeau.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/leblanc_mirabeau.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descrição, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Shelby Supercars Ultimate ' , ' Descrição Shelby Supercars Ultimate ' , ' http://www.livroandroid.com.br/livro/carros/ luxo / Shelby_Supercars_Ultimate.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/shelby.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Pagani Zonda ' , ' Descrição Pagani Zonda ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Pagani_Zonda.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/pagani_zonda.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Koenigsegg CCX ' , ' Descrição Koenigsegg CCX ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Koenigsegg_CCX.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/koenigsegg.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descrição, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Mercedes SLR McLaren ' , ' Descrição Mercedes SLR McLaren ' , ' http://www.livroandroid.com.br/livro/carros/ luxo / Mercedes_McLaren.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/mclaren_slr.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Rolls Royce Phantom ' , ' Descrição Rolls Royce Phantom ' , ' http://www.livroandroid.com.br/livro/carros/ luxo / Rolls_Royce_Phantom.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/rolls_royce.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );
inserir em carro (nome, descricao, url_foto, url_video, latitude, longitude, tipo) VALORES ( ' Lexus LFA ' , ' Descrição Lexus LFA ' , ' http://www.livroandroid.com.br/livro/carros/luxo/ Lexus_LFA.png ' , ' http://www.livroandroid.com.br/livro/carros/luxo/lexus.mp4 ' , ' -23.564224 ' , ' -46.653156 ' , ' luxo ' );